testing

diff --git a/.github/workflows/pylint_check.yaml b/.github/workflows/pylint_check.yaml
--- a/.github/workflows/pylint_check.yaml
+++ b/.github/workflows/pylint_check.yaml
@@ -62,33 +62,33 @@ jobs:
 #        run: python3 -m pip install --no-cache-dir pygdal==2.2.3.*
 #
 #
-#      - name: Fetch/update pylint
-#        run: python3 -m pip install --upgrade --no-cache-dir pylint
-#        id: pylint-install
-#      - name: Fetch source code
-#        uses: actions/checkout@v2
-#        id: fetch-source
-#      - name: Finding files
-#        run: find . -type f -name "*.py" > action_pylint_files.txt
-#        id: find-python-files
-#      - name: Install system requirements from source
-#        shell: bash
-#        run: '[ -s "packages.txt" ] && (cat packages.txt | xargs apt-get install -y --no-install-recommends) || (echo "No addtional packages to install")'
-#        id: install-system-reqs
-#      - name: Install Python requirements from source
-#        shell: bash
-#        run: '[ -s "requirements.txt" ] && (python3 -m pip install --no-cache-dir -r requirements.txt) || (echo "No Python packages to install")'
-#        id: install-python-reqs
-#      - name: Run action pylint script
-#        shell: bash
-#        run: '[ -s "action_pylint.sh" ] && (chmod +x "action_pylint.sh" && ./action_pylint.sh) || (echo "Not running special action script - empty or not found")'
-#        id: run-special-action-script
-#      - name: Fetching pylint.rc file
-#        run: wget https://raw.githubusercontent.com/AgPipeline/Organization-info/master/pylint.rc
-#        id: fetch_pylint_resource
-#      - name: Listing
-#        run: ls -la
-#      - name: Files to lint
-#        run: cat action_pylint_files.txt
-#      - name: Running pylint
-#        run: cat action_pylint_files.txt | xargs python3 -m pylint --rcfile ./pylint.rc
+      - name: Fetch/update pylint
+        run: python3 -m pip install --upgrade --no-cache-dir pylint
+        id: pylint-install
+      - name: Fetch source code
+        uses: actions/checkout@v2
+        id: fetch-source
+      - name: Finding files
+        run: find . -type f -name "*.py" > action_pylint_files.txt
+        id: find-python-files
+      - name: Install system requirements from source
+        shell: bash
+        run: '[ -s "packages.txt" ] && (cat packages.txt | xargs apt-get install -y --no-install-recommends) || (echo "No addtional packages to install")'
+        id: install-system-reqs
+      - name: Install Python requirements from source
+        shell: bash
+        run: '[ -s "requirements.txt" ] && (python3 -m pip install --no-cache-dir -r requirements.txt) || (echo "No Python packages to install")'
+        id: install-python-reqs
+      - name: Run action pylint script
+        shell: bash
+        run: '[ -s "action_pylint.sh" ] && (chmod +x "action_pylint.sh" && ./action_pylint.sh) || (echo "Not running special action script - empty or not found")'
+        id: run-special-action-script
+      - name: Fetching pylint.rc file
+        run: wget https://raw.githubusercontent.com/AgPipeline/Organization-info/master/pylint.rc
+        id: fetch_pylint_resource
+      - name: Listing
+        run: ls -la
+      - name: Files to lint
+        run: cat action_pylint_files.txt
+      - name: Running pylint
+        run: cat action_pylint_files.txt | xargs python3 -m pylint --rcfile ./pylint.rc
